name: Build & Push
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://crpi-g1z7tic1gltl16q5.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: crpi-g1z7tic1gltl16q5.cn-hangzhou.personal.cr.aliyuncs.com/weskerlee-ocr/weskerlee-ocr:v1
